### ISSUE TITLE
NEU is no longer maintained, and the last update was in 2021

### ISSUE THREAD

**Issue by 25HoursaDay** [MicrocontrollersDev/Alternatives#101]
title

**Comment by MicrocontrollersDev** [comment]
NEU is being maintained by some of the staff in Moulberry’s Discord server. NEU 2.1 is currently pretty deep in development and you can download a build from their Actions or on Moulberry’s Discord server. The full 2.1 release will hopefully be soon. The new github is https://github.com/NotEnoughUpdates/NotEnoughUpdates
