### ISSUE TITLE
Fabric/Forge install guide / PolyMC

### ISSUE THREAD

**Issue by MicrocontrollersDev** [MicrocontrollersDev/Alternatives#110]
It might be useful to include a Forge/Fabric install guide for users as it's a bit less straightforward than clients, especially with how awful the default Minecraft launcher is.

It might also make sense to have a PolyMC guide for this since it's considerably easier. Quite frankly, the fewer people using the default Minecraft launcher, the happier the community is. This PolyMC guide would link to PolyMC's own guide and then possibly add our own info to better suit the audience the list is for.

**Comment by Zetvue** [comment]
yeah but where the fuck do we add this to

**Comment by MicrocontrollersDev** [comment]
my thoughts rn: make it its own thing and have either a note on top of each page or a thing in the homepage

**Comment by Zetvue** [comment]
seems good

**Comment by Mqisty** [comment]
whos gonna do it tho

**Comment by MicrocontrollersDev** [comment]
> whos gonna do it tho

heyyyyyyyyy

**Comment by MicrocontrollersDev** [comment]
but nah already got the fabric one forge one i just ~~steal~~ get heavily influenced from lizzy and polymc they already got a whole ass guide that can just link too not much to write after that

**Comment by Mqisty** [comment]
ez ctrl + c, ctrl + v :sleeping:

**Comment by Mqisty** [comment]
is there any plan for this or are you going to  do it "later"

**Comment by MicrocontrollersDev** [comment]
“later” but no i will do it just need some time to think it out

**Comment by MicrocontrollersDev** [comment]
on second thought seems like extra work that isn't too important, especially since this is mostly just alternatives and that's all. i feel like there are better guides than I can make that will stay up to date. if someone wants to pr it sure but not gonna do this myself

**Comment by Mqisty** [comment]
i dmed tireless about that guide idea but i never got a dm back 😔

**Comment by Mqisty** [comment]
i might just do it myself idk

**Comment by MicrocontrollersDev** [comment]
go ham bro

**Comment by Mqisty** [comment]
nobody would even use it tho 😔

**Comment by MicrocontrollersDev** [comment]
exactly lol

**Comment by Mqisty** [comment]
ima do it anyway 🤷
