### ISSUE TITLE
Change Deftu links to https://deftu.xyz

### ISSUE THREAD

**Issue by Deftu** [MicrocontrollersDev/Alternatives#118]
I really cba to do it myself, someone else do it pretty please

**Comment by Mqisty** [comment]
what links

**Comment by Deftu** [comment]
> what links

Contributor links

**Comment by MicrocontrollersDev** [comment]
moisty hasn’t completed this request in 3 minutes i pay him too much

**Comment by Mqisty** [comment]
i forgor

**Comment by Mqisty** [comment]
you only have one contributor link unless im blind

**Comment by Deftu** [comment]
> you only have one contributor link unless im blind

I have one in a ton of the lists

**Comment by Mqisty** [comment]
> I have one in a ton of the lists

you sure? vscode search only comes up with 1 link which is in `contributors.md`

**Comment by Deftu** [comment]
> > I have one in a ton of the lists
> 
> you sure? vscode search only comes up with 1 link which is in `contributors.md`

I remember seeing myself in some other files too...

**Comment by Mqisty** [comment]
> > > I have one in a ton of the lists
> > 
> > you sure? vscode search only comes up with 1 link which is in `contributors.md`
> 
> I remember seeing myself in some other files too...

idk i cant find any other links and firefox keeps crashing when i open the repo

**Comment by Deftu** [comment]
> > > > I have one in a ton of the lists
> > > 
> > > 
> > > you sure? vscode search only comes up with 1 link which is in `contributors.md`
> > 
> > 
> > I remember seeing myself in some other files too...
> 
> idk i cant find any other links and firefox keeps crashing when i open the repo

Eh just change the ones VS Code is aware of, it's fine

**Comment by Mqisty** [comment]
i forgor
