### ISSUE TITLE
Tellinq's Potion Effects Mod is not easily downloadable.

### ISSUE THREAD

**Issue by MystycTrolls** [MicrocontrollersDev/Alternatives#144]
Not sure if this is really a problem but is there any other alternative?

**Comment by MicrocontrollersDev** [comment]
Right now you'll have to use GitHub Actions (I should edit the links to redirect to the Actions tab) but that requires being logged into github, which id imagine most people arent. There are no good alternatives I have to his mod as all other potion hud mods are old and can cause weird issues (powns). I might just rehost direct downloads to Tellinq's until he releases a full release

**Comment by MystycTrolls** [comment]
Can you link me how to build the mod?

**Comment by MicrocontrollersDev** [comment]
You dont have to build it, just go to https://github.com/Tellinq/Potion-Effects/actions, click on the latest one, scroll to the bottom and download the artifacts. It'll download a zip file and the mod will be inside there

**Comment by MystycTrolls** [comment]
Thanks I couldnt figure it out

**Comment by MicrocontrollersDev** [comment]
i changed all download links to be easier now
