### ISSUE TITLE
SBE uses outdated list of features

### ISSUE THREAD

**Issue by MicrocontrollersDev** [MicrocontrollersDev/Alternatives#19]
i have no clue what to do about this

why don’t they provide people with a list of features? it’s a paid mod! are people just buying it because some random person on the internet said it was good? do they not know what they are paying for? “premium mod” yeah right

**Comment by Lucasyh** [comment]
I recorded a video with everything in /sbe menu
https://www.youtube.com/watch?v=dluIhwVqNvg
I actually paid $5 so bruh
hope this helps you

**Comment by MicrocontrollersDev** [comment]
> I recorded a video with everything in /sbe menu
> https://www.youtube.com/watch?v=dluIhwVqNvg
> I actually paid $5 so bruh
> hope this helps you

This is exactly what I needed! Thanks!
