### ISSUE TITLE
Design inconsistent between different lists

### ISSUE THREAD

**Issue by MicrocontrollersDev** [MicrocontrollersDev/Alternatives#3]
Each list has its own style and there is little consistency between them. Not that big of a deal but BLC needs to be updated as it is extremely outdated (pretty much the same as Napkin's fork of Max's original list).

SBE is also very different, but seeing as that one is pretty informal, I don't think it matters much. The closest resemblance between any is LabyMod's and Lunar's, and if I do end up redesigning my lists, I should go with a style similar to those.

This issue is mainly to have a constant reminder that BLC and SBC need to be updated but also that I should come up with a design that all lists should follow.

**Comment by LizzyMaybeDev** [comment]
bad
