### ISSUE TITLE
Is There a Fabric Version of the Alternatives?

### ISSUE THREAD

**Issue by ThimothyXYZ123** [MicrocontrollersDev/Alternatives#35]
Is there a fabric version of the Alternatives for 1.17+?

**Comment by MicrocontrollersDev** [comment]
I would like to make 1.17+ fabric versions for the client alternatives in specific but I'm not sure how to go about it. I'll think about it and maybe start something for it soon.

**Comment by ghost** [comment]
Idk man i feel like people can just use migrating to latest and then just do crtl + f to find a mod. Plus some mods like hypixel mods i dont think anyone is gonna use for the latest version. And also there are only like afew replacement mods for the latest version being perspective mod redux, krono hud and perhaps advanced chat

**Comment by MicrocontrollersDev** [comment]
if someone else wants to do something then they can. i’m personally not going to work on this until newer versions become more popular for client users

**Comment by Zetvue** [comment]
This exists now. Go [here](https://github.com/MicrocontrollersDev/Alternatives/tree/main/LV).
