### ISSUE TITLE
Moulberrys Motionblur

### ISSUE THREAD

**Issue by ReissSchlingel** [MicrocontrollersDev/Alternatives#54]
How can i config moulberrys motionblur?

**Comment by MicrocontrollersDev** [comment]
it does not have any config options and moulberry is no longer working on it. there is a new blur mod by djtheredstoner that is in development and has config options called monkeyblur, but it is not released yet

**Comment by couleurm** [comment]
I'm very curious to see what these new motion blur mods offer 😋

**Comment by MicrocontrollersDev** [comment]
W-OVERFLOW also seems to be making their own motionblur

**Comment by SolarisAVR** [comment]
Moulberrys motionblur doesnt work from water and fire :C btw can i see what W-OVERFLOW and monkeyblur motionblur looks like

**Comment by MicrocontrollersDev** [comment]
i wasn’t able to build monkeyblur and i don’t think anything has been pushed to w’s motion blur yet

**Comment by SolarisAVR** [comment]
oof, does monkeyblur looks exactly like lunar?

**Comment by Wyvest** [comment]
> Moulberrys motionblur doesnt work from water and fire :C btw can i see what W-OVERFLOW and monkeyblur motionblur looks like

we havent made ours (w-overflow) yet but should look something like https://developer.nvidia.com/gpugems/gpugems3/part-iv-image-effects/chapter-27-motion-blur-post-processing-effect
