### ISSUE TITLE
Is the mod menu a Minecraft mod or directly coded into the client?

### ISSUE THREAD

**Issue by ohxxm** [MicrocontrollersDev/Alternatives#69]
If its a Minecraft mod, what is it called? If not, how can you implement this in your own Forge pack?

**Comment by MicrocontrollersDev** [comment]
Sorry, I’m a bit confused by this question. Do you mean the “Mod Options” button that comes up when you press escape in 1.8.9? That is built into forge but not many mods use it due to it being pretty old, and I can help you solve any issue you may have with opening or creating mod menus. If you are on 1.17 or 1.18, there is a fabric mod called “Mod Menu” which is its own mod and is much more modern and widely used and I can help you find more resources on using it if this is what you mean.

**Comment by ghost** [comment]
Nice issue number btw

**Comment by ohxxm** [comment]
> Sorry, I’m a bit confused by this question. Do you mean the “Mod Options” button that comes up when you press escape in 1.8.9? That is built into forge but not many mods use it due to it being pretty old, and I can help you solve any issue you may have with opening or creating mod menus. If you are on 1.17 or 1.18, there is a fabric mod called “Mod Menu” which is its own mod and is much more modern and widely used and I can help you find more resources on using it if this is what you mean.

I am talking about how PvP Clients like Lunar or Badlion have a mod menu when you press right shift.

**Comment by MicrocontrollersDev** [comment]
Ah thanks, I understand what you mean now. Unfortunately Forge doesn’t have anything like that as of yet, but there are projects working on it. Currently, to open the menu for mods, you have to use their commands. For example, to open Patcher settings, you have to type /patcher in chat. As I said, there are projects to unify everything into one menu, such as Essential and OneConfig, but those features aren’t released yet and will take a while, and even then, mod developers have to adapt them.

**Comment by ohxxm** [comment]
> Ah thanks, I understand what you mean now. Unfortunately Forge doesn’t have anything like that as of yet, but there are projects working on it. Currently, to open the menu for mods, you have to use their commands. For example, to open Patcher settings, you have to type /patcher in chat. As I said, there are projects to unify everything into one menu, such as Essential and OneConfig, but those features aren’t released yet and will take a while, and even then, mod developers have to adapt them.

Ok, thanks for your response. Closing this issue.
