### ISSUE TITLE
Banned from Minemen Club because of Sk1er OAM

### ISSUE THREAD

**Issue by ImFabulous** [MicrocontrollersDev/Alternatives#85]
The mod gets people false banned 
(I myself got banned from mmc and the staff told me that it was this mod)

**Comment by Wyvest** [comment]
> The mod gets people false banned (I myself got banned from mmc and the staff told me that it was this mod)

Both sides deny it's their issue, ~~for now just disable punching (should fix the issue mostly)~~ use overflowanimations

**Comment by SystemlessDev** [comment]
Not to forget that the folks over at MMC refuse to cooperate nor show any proof that it's in fact our old animation mod's fault

I wouldn't recommend blindly listening to them considering their general aggressiveness towards forge mods

**Comment by ImFabulous** [comment]
Alr

**Comment by Zetvue** [comment]
shut the up

**Comment by Zetvue** [comment]
If you get banned from MMC because of OAM, their anticheat is horrible. Do what Wyvest said.
If you still want punching, you may have to use Spiderfrog OAM. (I recommend not using it because of their bloat)
> for now just disable punching (should fix the issue mostly)

**Comment by RayDeeUx** [comment]
overflowanimations was released so use sk1er oam **_and_** overflowanimations

overflowanimations has an option to switch the hit animation to use spiderfrog’s, which won’t get you banned on MMC
