### ISSUE TITLE
[Suggestion] Make a GitHub Pages

### ISSUE THREAD

**Issue by couleurm** [MicrocontrollersDev/Alternatives#88]
Hey Micro, you really should make a website using [Pages](https://pages.github.com) out of your .MD's! It'd make it much more user-friendly and pretty than on a code-project oriented website

**Comment from Zetvue:**
Looks like this is becoming a reality!
Once the site is fixed, this issue will be closed.

**Comment by Zetvue** [comment]
How exactly would it be more user friendly?
It really isn't that hard to just click on an MD to read it.

**Comment by UnderscoreRayless** [comment]
Tons of people don't know how github works, all the buttons might confuse them on how to view the file, I think this is a good idea granted it would take a decent bit of effort

**Comment by MicrocontrollersDev** [comment]
I was considering this for a while but have absolutely no motivation to do any of the work. Proudmuslim used to host my lists on his own pages around a year ago and it was pretty nice. This is something I may look into in the upcoming months.

**Comment by proudmuslim-dev** [comment]
I'd recommend using [mdbook](https://github.com/rust-lang/mdBook#mdbook=) for this, as I did


The way I set the website up can still be found at the [repo](https://github.com/proudmuslim-dev/proudmuslim.tech)- feel free to borrow anything you want from it

**Comment by MicrocontrollersDev** [comment]
Epic, thanks!

**Comment by Deftu** [comment]
I also recommend [MkDocs](https://www.mkdocs.org/). I personally think it looks pretty good too. The [JDA wiki](http://jda.wiki/) uses it

**Comment by Zetvue** [comment]
Looks like this is becoming a reality!
Once the site is fixed, this issue will be closed.

**Comment by Deftu** [comment]
Done. A GitHub Pages site made using MkDocs is now up [here](https://microcontrollersdev.github.io/Alternatives/).
