### ISSUE TITLE
MoreCosmeticsmod

### ISSUE THREAD

**Issue by Kolpixx** [MicrocontrollersDev/Alternatives#93]
https://github.com/MicrocontrollersDev/Alternatives/issues/91#issuecomment-1114332495

You can buy some Cosmetics, but most of them are free. You can download the mod and see it yourself.

**Comment by Kolpixx** [comment]
Oh sorry, I didn’t saw the message right after my message. I only saw the last 2 messages.

**Comment by Kolpixx** [comment]
But just one question where does the mod exactly break the EULA of MInecraft.

**Comment by MicrocontrollersDev** [comment]
Only Mojang is allowed to distribute capes or anything resembling capes. Other cosmetics are fine but capes are against EULA. This is why ModCore/Essential no longer sells capes.

**Comment by Kolpixx** [comment]
Ah ok. So is Lunar, Badlion, Labymod etc. also against the EULA?

**Comment by MicrocontrollersDev** [comment]
Yes. And OptiFine. However, Mojang just doesn't do anything about it because they just don't care for some reason. The only group that I know of that was forced to take down their capes was ModCore.

Edit: "they weren't happy with it so we made the decision to kill capes"
